package org.texttechnologylab.udav.widgets.svgtolatex;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.UncheckedIOException;
import java.nio.charset.StandardCharsets;
import java.util.Collections;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Locale;
import java.util.Map;
import java.util.Set;
import java.util.function.Predicate;

/**
 * Character advance widths, read from a table checked in beside this class rather
 * than measured from the fonts installed on the machine.
 * <p>
 * Text chunks are positioned by the width of the preceding chunk, so these widths
 * decide where every {@code <tspan>} lands. Taking them from a fixed table is what
 * keeps an export identical from one machine to the next, the Docker image included.
 * The table is generated by the VecTikZ tooling, the only code that touches AWT, and
 * has to be regenerated when a document names a font it does not carry.
 * <p>
 * AWT shapes Arabic, Indic and Tibetan runs, so for those scripts a per-character sum
 * is wider than the shaped run. Whether a font is available is also answered from the
 * table ({@link #isAvailable}), not from the JVM.
 */
public final class FontMetrics {

    private FontMetrics() {
    }

    /** Size the table was measured at; dividing by it keeps the ratio precise. */
    public static final int MEASURE_SIZE = 1000;

    /** Where the generated table sits on the classpath, next to this class. */
    private static final String RESOURCE = "font-metrics.txt";

    /** Bumped whenever the record layout changes, so a stale file fails loudly. */
    private static final int FORMAT_VERSION = 1;

    // -----------------------------------------------------------------------
    // Family resolution
    // -----------------------------------------------------------------------

    /**
     * Maps an SVG {@code font-family} list onto the family to measure with,
     * using the table's notion of which fonts exist.
     */
    public static String resolveFamily(String cssFamilyList) {
        return resolveFamily(cssFamilyList, FontMetrics::isAvailable);
    }

    /**
     * The resolution itself, with the availability question left open.
     * <p>
     * FontTableDump calls this with AWT as the oracle while it generates the table;
     * everything else calls the one-argument form, which asks the finished table.
     * Both have to select the same entry of a list, or the table would hold metrics
     * for a font the converter never chooses.
     * <p>
     * A generic keyword is honoured before availability is consulted, so
     * {@code "Georgia, serif"} measures as a serif whether or not Georgia is present.
     */
    public static String resolveFamily(String cssFamilyList, Predicate<String> isAvailable) {
        if (cssFamilyList == null || cssFamilyList.isBlank()) return "SansSerif";
        for (String candidate : cssFamilyList.split(",")) {
            String name = candidate.trim().replaceAll("^[\"']|[\"']$", "");
            if (name.isEmpty()) continue;
            switch (name.toLowerCase(Locale.ROOT)) {
                case "serif", "times", "times new roman", "georgia" -> { return "Serif"; }
                case "sans-serif", "sans", "helvetica", "arial", "verdana" -> { return "SansSerif"; }
                case "monospace", "mono", "courier", "courier new" -> { return "Monospaced"; }
                default -> {
                    // Present: measure with it. Absent: try the next entry, as a
                    // browser does, so "'Arial Unicode MS', Georgia, serif" measures
                    // as a serif rather than in the default sans.
                    if (isAvailable.test(name)) return name;
                }
            }
        }
        return "SansSerif";
    }

    /** Whether the table carries real metrics for a concrete family name. */
    public static boolean isAvailable(String name) {
        return Tables.INSTANCE.available.contains(name.trim().toLowerCase(Locale.ROOT));
    }

    // -----------------------------------------------------------------------
    // Measurement
    // -----------------------------------------------------------------------

    /**
     * How wide {@code text} is in the given family and weight, at {@link #MEASURE_SIZE}.
     * Summed per code point rather than per {@code char}, so an astral character
     * counts once instead of as two unpaired surrogates.
     */
    public static double advanceAtMeasureSize(String text, String family, boolean bold) {
        if (text == null || text.isEmpty()) return 0;
        AdvanceTable table = Tables.INSTANCE.tableFor(family, bold);
        double total = 0;
        for (int cp : text.codePoints().toArray()) {
            Double w = table.widths.get(cp);
            total += w == null ? table.fallback : w;
        }
        return total;
    }

    // -----------------------------------------------------------------------
    // The frozen table
    // -----------------------------------------------------------------------

    /** Advance widths for one family and weight, keyed by code point. */
    private record AdvanceTable(Map<Integer, Double> widths, double fallback) {
    }

    /**
     * Holder so the table is read on first measurement rather than on class load.
     * FontTableDump calls {@link #resolveFamily(String, Predicate)} while it is
     * generating the file this reads, and must not trip over a missing or stale one.
     */
    private static final class Tables {

        static final Tables INSTANCE = load();

        /** Lower-cased family names the generator's machine could render. */
        final Set<String> available;

        /** Canonical key ({@code family} or {@code family|bold}) to its widths. */
        final Map<String, AdvanceTable> advances;

        /** Keys whose metrics are identical to another entry, mapped to it. */
        final Map<String, String> aliases;

        Tables(Set<String> available, Map<String, AdvanceTable> advances, Map<String, String> aliases) {
            this.available = available;
            this.advances = advances;
            this.aliases = aliases;
        }

        /**
         * The table for a family and weight, following aliases.
         * <p>
         * Falls back to the sans-serif metrics, resolved through the alias map as
         * well, since the canonical entry for a set of identical families is whichever
         * name the generator emitted first. A family the generator never saw can only
         * come from a document outside the corpus, and substituted sans is what AWT
         * would most likely have given it.
         */
        AdvanceTable tableFor(String family, boolean bold) {
            String suffix = bold ? "|bold" : "";
            String key = family + suffix;
            AdvanceTable direct = advances.get(aliases.getOrDefault(key, key));
            if (direct != null) return direct;
            String fallbackKey = "SansSerif" + suffix;
            return advances.get(aliases.getOrDefault(fallbackKey, fallbackKey));
        }
    }

    /**
     * Reads the generated table: tab-separated {@code available}, {@code table} and
     * {@code alias} records. Widths are written in Java's shortest round-trip form,
     * so parsing them back yields the identical double.
     */
    private static Tables load() {
        Set<String> available = new HashSet<>();
        Map<String, AdvanceTable> advances = new HashMap<>();
        Map<String, String> aliases = new HashMap<>();

        try (InputStream in = FontMetrics.class.getResourceAsStream(RESOURCE)) {
            if (in == null) {
                throw new IllegalStateException(
                        "Missing " + RESOURCE + " on the classpath; the converter cannot lay "
                                + "out text without the frozen font metrics. The file is checked in "
                                + "next to this class, so a build that drops it is the likely cause.");
            }
            BufferedReader reader = new BufferedReader(
                    new InputStreamReader(in, StandardCharsets.UTF_8));
            String line;
            while ((line = reader.readLine()) != null) {
                if (line.isEmpty() || line.charAt(0) == '#') continue;
                String[] f = line.split("\t", -1);
                switch (f[0]) {
                    case "version" -> {
                        if (!f[1].equals(String.valueOf(FORMAT_VERSION))) {
                            throw new IllegalStateException(
                                    RESOURCE + " is format version " + f[1] + ", expected "
                                            + FORMAT_VERSION + ": the table and this class are out "
                                            + "of step.");
                        }
                    }
                    case "available" -> available.add(f[1]);
                    case "alias" -> aliases.put(f[1], f[2]);
                    case "table" -> advances.put(f[1], parseTable(f[2], f[3]));
                    default -> throw new IllegalStateException(
                            "Unknown record in " + RESOURCE + ": " + f[0]);
                }
            }
        } catch (IOException e) {
            throw new UncheckedIOException("Cannot read " + RESOURCE, e);
        }

        if (!advances.containsKey("SansSerif")) {
            throw new IllegalStateException(
                    RESOURCE + " carries no SansSerif table, which every lookup falls back to.");
        }
        return new Tables(Collections.unmodifiableSet(available),
                Collections.unmodifiableMap(advances),
                Collections.unmodifiableMap(aliases));
    }

    /** {@code "32:278 33:295 ..."} plus the width of an unmapped code point. */
    private static AdvanceTable parseTable(String fallback, String widths) {
        Map<Integer, Double> map = new HashMap<>();
        for (String pair : widths.split(" ")) {
            if (pair.isEmpty()) continue;
            int colon = pair.indexOf(':');
            map.put(Integer.parseInt(pair.substring(0, colon)),
                    Double.parseDouble(pair.substring(colon + 1)));
        }
        return new AdvanceTable(Collections.unmodifiableMap(map), Double.parseDouble(fallback));
    }
}
